config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  namespace :admin do
    resources :skills
    resources :tags
  end

  resources :users, only: [:create, :new, :edit, :show, :update] do
    resources :skills
  end

  namespace :all do
    resources :skills, only: [:index]
  end

  namespace :guest do
    resources :skills, only: [:index]
  end

  resources :tags, only: [:show, :index]

end

app/models/skill.rb
# Model for the skill
class Skill < ActiveRecord::Base
  belongs_to :user
  has_many :skills_tags, dependent: :destroy
  has_many :tags, through: :skills_tags

  validates :name,        presence: true
  validates :description, presence: true

  def tag_list
    tags.join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(',').collect do |s|
      s.strip.downcase.capitalize
    end.uniq
    new_or_found_tags = tag_names.collect do |name|
      Tag.find_or_create_by(name: name)
    end
    self.tags = new_or_found_tags
  end
end

app/models/skills_tag.rb
# Join table for skills and tags
class SkillsTag < ActiveRecord::Base
  belongs_to :skill
  belongs_to :tag
end

app/models/tag.rb
# Model for tags
class Tag < ActiveRecord::Base
  has_many :skills_tags
  has_many :skills, through: :skills_tags

  validates :name, presence:   true,
                   uniqueness: true

  def to_s
    name
  end
end

app/models/user.rb
# Model for the user
class User < ActiveRecord::Base
  has_secure_password

  has_many :skills

  validates :username,      presence:   true,
                            uniqueness: true

  validates :password,      presence: true

  validates :email_address, presence:   true,
                            uniqueness: true

  validates :phone_number,  presence:   true,
                            uniqueness: true

  validates :role, presence: true

  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
# BaseController for the admin namespace
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: '/public/error' unless current_admin?
  end
end

app/controllers/admin/skills_controller.rb
# Skills Controller for the admin namespace, admin crud for skills
class Admin::SkillsController < Admin::BaseController
  def index
    @skills = Skill.all
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    if @skill.update(skill_params)
      redirect_to admin_skill_path(@skill)
    else
      render :edit
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy
    redirect_to admin_skills_path
  end

  private

  def skill_params
    params.require(:skill).permit(:name, :description, :tag_list)
  end
end

app/controllers/admin/tags_controller.rb
# Tags controller for the admin namespace, admin crud for tags
class Admin::TagsController < Admin::BaseController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @skills = @tag.skills
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to admin_tag_path(@tag)
    else
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to admin_tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/all/skills_controller.rb
# Skills controller for the all namespace, skill index for all users
class All::SkillsController < ApplicationController
# love this restful controller! Good stuff my dude!
  def index
    @skills = Skill.all
  end
end

app/controllers/application_controller.rb
# This is the general Application Controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :render_error
  helper_method :current_user
  before_action :require_log_in

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def require_log_in
    render file: '/public/error' unless current_user
  end

  def render_error
    render file: '/public/not_found'
  end
end

app/controllers/guest/skills_controller.rb
# Skills controller for the guests namespace, skill index for guests
class Guest::SkillsController < ApplicationController
  skip_before_action :require_log_in

  def index
    @skills = Skill.all
  end
end

app/controllers/sessions_controller.rb
# This is the session controller that controls current_user
class SessionsController < ApplicationController
  skip_before_action :require_log_in

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:error] = 'Please make sure all fields are correct...'
      render(:new)
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/skills_controller.rb
# This is the skills controller, crud for skills
class SkillsController < ApplicationController
  def new
    @skill = current_user.skills.new
  end

  def create
    #no need for the @ 
    @skill = Skill.create(skill_params)
    @skill.user = current_user
    if @skill.save
      redirect_to user_skill_path(current_user, @skill)
    else
      render :new
    end
  end

  def show
    @skill = Skill.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def index
    @skills = Skill.all
    @user = User.find(params[:user_id])
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    if @skill.update(skill_params)
      redirect_to user_skill_path(current_user, @skill)
    else
      render :edit
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy
    redirect_to user_skills_path(current_user)
  end

  private

  def skill_params
    params.require(:skill).permit(:name, :description, :tag_list)
  end
end

app/controllers/tags_controller.rb
# This is the tags controller, controls showing tags
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @skills = @tag.skills
  end
end

app/controllers/users_controller.rb
# This is the users controller, crud for users
class UsersController < ApplicationController
  skip_before_action :require_log_in, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:error] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username,
                                 :password,
                                 :email_address,
                                 :phone_number)
  end
end

app/controllers/welcome_controller.rb
# This is the welcome controller, controls homepage
class WelcomeController < ApplicationController
  skip_before_action :require_log_in

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/skills/_error.html.erb
<div class="text-center">
  <h1><img src="http://teecraze.com/wp-content/uploads/accessdenied.jpg"></h1>
  <h1>Error 403</h1>
  <br>
</div>

app/views/admin/skills/edit.html.erb
<% if current_user.admin? %>
  <div class="row well form-group">
    <div class="col-md-4 text-center">
      <h1> Edit Skill </h1>
    </div>
    <div class="col-md-8">
      <%= form_for [:admin, @skill] do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
        <%= f.label :tag_list %>
        <%= f.text_area :tag_list, class: "form-control" %>
        <br>
        <%= f.submit class: "btn btn-primary col-md-offset-4" %>
      <% end %>
    </div>
  </div>
<% else %>
  <%= render partial: 'shared/error' %>
<% end %>

app/views/admin/skills/index.html.erb
<div class="container-fluid well">
  <div class="jumbotron text-center">
    <h1>Admin Skills</h1>
  </div>
  <div class="row">
    <% @skills.each do |skill| %>
      <div class="col-md-4 text-center">
          <h3><%= link_to skill.name, admin_skill_path(skill), class: "text-muted" %></h3>
          <p>
            <%= skill.description %>
          </p>
        </div>
    <% end %>
  </div>
</div>

app/views/admin/skills/show.html.erb
<div class="container-fluid">
  <div class="jumbotron">
    <div class="row">
      <div class="text-center col-md-2">
        <h3><%= link_to @skill.user.username, @skill.user, class: "text-muted" %></h3>
      </div>
      <div class="text-center col-md-8">
        <h1> <%= @skill.name %> </h1><br>
      </div>
      <div class="text-center col-md-2">
        <h3><%= link_to "Edit Skill", edit_admin_skill_path(@skill), class: "btn btn-warning" %></h3>
      </div>
    </div>
    <div class="row text-center">
      <p>
        <%= @skill.description %>
      </p>
      <body>
        <% @skill.tags.each do |tag| %>
          <%= link_to tag.name, admin_tag_path(tag), class: "text-muted" %>,
        <% end %>
      </body>
    </div><br><br>
    <div class="row text-center">
      <%= link_to "Delete", admin_skill_path(@skill), class: "btn btn-danger btn-sm", method: :delete  %>
    </div>
  </div>
</div>

app/views/admin/tags/edit.html.erb
<div class="row well form-group">
  <div class="col-md-4 text-center">
    <h1> Edit Tag </h1>
  </div>
  <div class="col-md-8">
    <%= form_for [:admin, @tag] do |f|  %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control"%>
      <br>
      <%= f.submit class: "btn btn-primary col-md-offset-4"%>
    <% end %>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="container-fluid well">
  <div class="jumbotron text-center">
    <h1>Admin Tags</h1>
  </div>
  <div class="row">
    <% @tags.each do |tag| %>
      <div class="col-md-4 text-center">
        <body>
          <h3><%= link_to tag.name, admin_tag_path(tag), class: "text-muted" %></h3> <p> Skills: <%= tag.skills.count %></p>
        </body>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/tags/show.html.erb
<div class="container-fluid well">
  <div class="jumbotron text-center">
    <h1><%= @tag.name.capitalize %>'s Skills</h1>
    <div class="row">
      <div class="col-md-4 col-md-offset-2">
        <h3><%= link_to "Edit Tag", edit_admin_tag_path(@tag), class: "btn btn-warning" %></h3>
      </div>
      <div class="col-md-4">
        <h3><%= link_to "Delete", admin_tag_path(@tag), class: "btn btn-danger btn-sm", method: :delete  %></h3>
      </div>
    </div>
  </div>
  <div class="row">
    <% @skills.each do |skill| %>
      <div class="col-md-4 text-center">
          <h3><%= link_to skill.name, admin_skill_path(skill), class: "text-muted" %></h3>
          <p>
            <%= skill.description %>
          </p>
        </div>
    <% end %>
  </div>
</div>

app/views/all/skills/index.html.erb
<div class="container-fluid well">
  <div class="jumbotron text-center">
    <h1>All Skills</h1>
  </div>
  <div class="row">
    <% @skills.each do |skill| %>
      <div class="col-md-4 text-center">
          <h3><%= link_to skill.name, user_skill_path(skill.user, skill), class: "text-muted" %></h3>
          <p>
            <%= skill.description %>
          </p>
        </div>
    <% end %>
  </div>
</div>

app/views/guest/skills/index.html.erb
<div class="container-fluid well">
  <div class="jumbotron text-center">
    <h1>All Skills</h1>
    <br>
    <p>
      Sign up to see details about our Users!
    </p>
  </div>
  <div class="row">
    <% @skills.each do |skill| %>
      <div class="col-md-4 text-center">
          <h3><%= skill.name %></h3>
          <p>
            <%= skill.description %>
          </p>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class='navbar navbar-default navbar-static-top col-md-12'>
    <a href='/' class='navbar-brand'>Captain</a>
    <% if current_user %>
      <ul class="nav navbar-nav">
        <li><%= link_to "#{current_user.username}", user_path(current_user) %></li>
        <% if current_user.admin? %>
          <li><%= link_to "Admin Tags", admin_tags_path %>
          <li><%= link_to "Admin Skills", admin_skills_path %></li>
        <% end %>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
      <li><%= link_to "All Skills", all_skills_path %></li>
      <li><%= link_to "Tags", tags_path %></li>
      <li><%= link_to "Logout", logout_path, method: :delete %></li>
      </ul>
    <% else %>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "All Skills", guest_skills_path %></li>
    </ul>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/navbar' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
</body>
</html>

app/views/skills/_skill_form.html.erb
<%= form_for [current_user, @skill] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>
  <%= f.label :tag_list %>
  <%= f.text_area :tag_list, class: "form-control" %>
  <br>
  <%= f.submit class: "btn btn-primary col-md-offset-4" %>
<% end %>

app/views/skills/edit.html.erb
<div class="row well form-group">
  <div class="col-md-4 text-center">
    <h1> Edit Skill </h1>
  </div>
  <div class="col-md-8">
    <%= render partial: 'skill_form' %>
  </div>
</div>

app/views/skills/index.html.erb
<% if @user == current_user %>
  <div class="container-fluid well">
    <div class="jumbotron text-center">
      <h1>Your Skills</h1>
    </div>
    <div class="row">
      <% current_user.skills.each do |skill| %>
        <div class="col-md-4 text-center">
          <h3><%= link_to skill.name, user_skill_path(current_user, skill), class: "text-muted" %></h3>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="container-fluid well">
    <div class="jumbotron text-center">
      <h1><%= @user.username %>'s Skills</h1>
    </div>
    <div class="row">
      <% @user.skills.each do |skill| %>
        <div class="col-md-4 text-center">
            <h3><%= link_to skill.name, user_skill_path(@user, skill), class: "text-muted" %></h3>
            <p>
              <%= skill.description %>
            </p>
          </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/skills/new.html.erb
<div class="row well form-group">
  <div class="col-md-4 text-center">
    <h1> Create a Skill </h1>
  </div>
  <div class="col-md-8">
    <%= render partial: 'skill_form' %>
  </div>
</div>

app/views/skills/show.html.erb
<% if @user == current_user && @user == @skill.user %>
  <div class="container-fluid">
    <div class="jumbotron">
      <div class="row">
        <div class="text-center col-md-2">
          <h3><%= link_to @skill.user.username, @skill.user, class: "text-muted" %></h3>
        </div>
        <div class="text-center col-md-8">
          <h1> <%= @skill.name %> </h1><br>
        </div>
        <div class="text-center col-md-2">
          <h3><%= link_to "Edit Skill", edit_user_skill_path(current_user, @skill), class: "btn btn-warning" %></h3>
        </div>
      </div>
      <div class="row text-center">
        <p>
          <%= @skill.description %>
        </p>
        <body>
          <% @skill.tags.each do |tag| %>
            <%= link_to tag.name, tag_path(tag), class: "text-muted" %>,
          <% end %>
        </body>
      </div><br><br>
      <div class="row text-center">
        <%= link_to "Delete", user_skill_path(current_user, @skill),  method: :delete, class: "btn btn-danger btn-sm"%>
      </div>
    </div>
  </div>
<% else %>
  <div class="container-fluid">
    <div class="jumbotron">
      <div class="row">
        <div class="text-center col-md-2">
          <h3><%= link_to @skill.user.username, @skill.user, class: "text-muted" %></h3>
        </div>
        <div class="text-center col-md-8">
          <h1> <%= @skill.name %> </h1><br>
        </div>
      </div>
      <div class="row text-center">
        <p>
          <%= @skill.description %>
        </p>
        <body>
          <% @skill.tags.each do |tag| %>
            <%= link_to tag.name, tag_path(tag), class: "text-muted" %>,
          <% end %>
        </body>
      </div>
    </div>
  </div>
<% end %>

app/views/tags/index.html.erb
<div class="container-fluid well">
  <div class="jumbotron text-center">
    <h1>All Tags</h1>
  </div>
  <div class="row">
    <% @tags.each do |tag| %>
      <div class="col-md-4 text-center">
        <body>
          <!-- DO NOT HAVE THIS IF STATEMENT IN THE ADMIN NAMESPACE -->
          <% if tag.skills.count > 0 %>
            <h3><%= link_to tag.name, tag_path(tag), class: "text-muted" %></h3> <p> Skills: <%= tag.skills.count %></p>
          <% end %>
        </body>
      </div>
    <% end %>
  </div>
</div>

app/views/tags/show.html.erb
<div class="container-fluid well">
  <div class="jumbotron text-center">
    <h1><%= @tag %>'s Skills</h1>
  </div>
  <div class="row">
    <% @skills.each do |skill| %>
      <div class="col-md-4 text-center">
          <h3><%= link_to skill.name, user_skill_path(skill.user, skill), class: "text-muted" %></h3>
          <p>
            <%= skill.description %>
          </p>
        </div>
    <% end %>
  </div>
</div>

app/views/users/_user_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username, class: "form-control" %>
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
  <%= f.label :email_address %>
  <%= f.text_field :email_address, class: "form-control" %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number, class: "form-control" %><br>
  <%= f.submit class: "btn btn-primary col-md-offset-4t" %>
<% end %>

app/views/users/edit.html.erb
<div class="row well form-group">
  <div class="col-md-4 text-center">
    <h1> Edit Information </h1>
  </div>
  <div class="col-md-8">
    <%= render partial: 'user_form' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row well form-group">
  <div class="col-md-4 text-center">
    <h1> Create Account </h1>
  </div>
  <div class="col-md-8">
    <%= render partial: 'user_form' %>
  </div>
</div>

app/views/users/show.html.erb
<% if @user == current_user %>
  <div class="container-fluid">
    <div class="jumbotron">
      <div class="text-center">
        <h1>Welcome <%= current_user.username %></h1>
      </div>
      <br><br>
      <div class="row text-center">
        <div class="col-md-2 col-md-offset-3">
          <%= link_to "Edit Information", edit_user_path(current_user), class: "btn btn-warning btn-xs" %>
        </div>
        <div class="col-md-2">
          <%= link_to "Create Skill", new_user_skill_path(current_user), class: "btn btn-success btn-xs" %>
        </div>
        <div class="col-md-2">
          <%= link_to "Your Skills", user_skills_path(current_user), class: "btn btn-primary btn-xs" %>
        </div>
      </div>
    </div>
  </div>
<% else %>
<div class="container-fluid">
  <div class="jumbotron">
    <div class="text-center">
      <h1><%= @user.username %>'s Homepage</h1>
    </div>
    <div class="row text-center">
      <p> Email: <%= @user.email_address %></p>
      <p> Phone: <%= @user.phone_number %></p>
      <br>
      <div class="col-md-2 col-md-offset-4">
        <%= link_to "All Skills", all_skills_path, class: "btn btn-success btn-xs" %>
      </div>
      <div class="col-md-2">
        <%= link_to "#{@user.username}'s' Skills", user_skills_path(@user), class: "btn btn-primary btn-xs" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/welcome/index.html.erb
<div class="jumbotron container-fluid">
  <div class="row well">
    <div class="text-center">
      <h1> Captain Jobs </h1>
    </div>
    <div class="row col-md-6 col-md-offset-3">
      <div class="text-center">
        <p> Welcome to Captain Jobs, here you will see various skills created by
          our users, each skill will contain a link to that users homepage where
          you will find the necessary contact info.</p>
      </div>
      <div class="row col-md-offset-2">
        <%= link_to "Login", login_path, :method => "get", class: 'btn btn-success' %>
        <%= link_to "Create Account", new_user_path, :method => "get", class: "btn btn-primary col-md-offset-6" %>
      </div>
    </div>
  </div>
</div>